// App
export const APP_LOADING = 'APP_LOADING';

// View
export const APP_VIEW_UPDATED = 'APP_VIEW_UPDATED';

export const APP_VIEW_TOGGLED = 'APP_VIEW_TOGGLED';

// Theme
export const APP_THEME_UPDATED = 'APP_THEME_UPDATED';

export const APP_THEME_TOGGLED = 'APP_THEME_TOGGLED';

// Misc
export const APP_MODAL_UPDATED = 'APP_MODAL_UPDATED';

export const APP_SHORTCUT_TOGGLED = 'APP_SHORTCUT_TOGGLED';

export const APP_ANIMATION_TOGGLED = 'APP_ANIMATION_TOGGLED';

// Category
export const APP_CATEGORY_UPDATED = 'APP_CATEGORY_UPDATED';

export const APP_CATEGORY_INSERTED = 'APP_CATEGORY_INSERTED';

// Collapsed
export const APP_COLLAPSED_HEADER_TOGGLED = 'APP_COLLAPSED_HEADER_TOGGLED';

export const APP_COLLAPSED_SIDEBAR_TOGGLED = 'APP_COLLAPSED_SIDEBAR_TOGGLED';

export const APP_COLLAPSED_CATEGORY_TOGGLED = 'APP_COLLAPSED_CATEGORY_TOGGLED';

// Calendar
export const APP_SELECTED_DAY_UPDATED = 'APP_SELECTED_DAY_UPDATED';

export const APP_SELECTED_YEAR_UPDATED = 'APP_SELECTED_YEAR_UPDATED';

export const APP_SELECTED_MONTH_UPDATED = 'APP_SELECTED_MONTH_UPDATED';
