export const MODAL_SECTIONS = {
	CLOSED: 'CLOSED',
	SEARCH: 'SEARCH',
	SETTINGS: 'SETTINGS',
	SHORTCUTS: 'SHORTCUTS',
	CREATE_EVENT: 'CREATE_EVENT',
	CREATE_CATEGORY: 'CREATE_CATEGORY',
}

export default {
	MODAL_SECTIONS,
}
